stages:
  prepare:
    cmd: python src/prepare.py data/data.csv
    deps:
    - data/data.csv
    - src/prepare.py
    outs:
    - data/prepared
  train:
    cmd: python src/train.py data/prepared model.pkl
    deps:
    - data/prepared
    - src/train.py
    params:
    - train.model
    - train.seed
    - train.split
    outs:
    - model/model.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl data/prepared scores.json predicted.csv ROC_AUC_curve.png
    deps:
    - data/prepared
    - model/model.pkl
    - src/evaluate.py
    params:
    - evaluate.model
    - evaluate.seed
    - evaluate.split
    metrics:
    - metrics/scores.json:
        cache: false
    plots:
    - plots/predicted.csv:
        cache: false
    - plots/ROC_AUC_curve.png:
        cache: false
